apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: acy642-default
  labels:
    service: postgres
spec:
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: "/var/www/html/data"
              name: postgres-volume
          ports:
            - containerPort: 5432
              protocol: TCP
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: acy642-default
  labels:
    service: postgres
spec:
   ports:
     - name: http
       port: 5432
       protocol: TCP
       targetPort: 5432
   selector:
    service: postgres
   type: ClusterIP