kind: ServiceAccount
apiVersion: v1
metadata:
    name: gitlab-sa
    namespace: acy642-default

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: gitlab-sa-rb
    namespace: acy642-default
subjects:
    - kind: ServiceAccount
      name: gitlab-sa
      namespace: acy642-default
roleRef:
    kind: ClusterRole
    name: kiosk-space-admin
    apiGroup: rbac.authorization.k8s.io
